### ISSUE TITLE
Turf Discrepancy

### ISSUE THREAD

**Issue by sjosias** [morganherlocker/oakland-tonight#11]
Hi Morgan

There seems to be a discrepancy between the turf-js API and the turf.min.js source code. The featureCollection function in the helper section of the API exhibits the following function definition:
- turf.featureCollection(features);

With the 'C' as capital, (If I understand correctly, this is the general standard for Javascript?), however, in the  source code the function is defined with a lowercase c, as follows: 'featurecollection(features)';

Thanks for the library, it is rather useful and the documentation is fairly neat.

**Comment by morganherlocker** [comment]
Wrong repo ;)
